# From https://docs.haskellstack.org/en/stable/travis_ci/
sudo: false

language: generic

cache:
  directories:
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

env:
  - WEEK_DIR=01-intro
  - WEEK_DIR=02-adt

install:
  - cd $WEEK_DIR && stack --no-terminal --install-ghc test --only-dependencies

script:
  - cd $WEEK_DIR && stack --no-terminal test --haddock --no-haddock-deps